baseurl = "https://exitcodezero.io/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Brian Hines"
title = "Brian Hines"
pluralizelisttitles = false
enableEmoji = true
uglyurls = true

[permalinks]
words = "words/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
lang = "en"
github = "projectweekend"
linkedin = "briandhines"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
